from pathlib import Path
from transformers import AutoTokenizer, AutoModelForCausalLM


class InstructionSafetyChecker:
    def __init__(self):
        base_dir = Path(__file__).resolve().parent.parent
        self.policy_path = base_dir / "INSTRUCTION.md"
        self.model_path = base_dir / "models" / "qwen2.5-0.5b-instruct"

        self.policy = self.policy_path.read_text(encoding="utf-8")

        self.tokenizer = AutoTokenizer.from_pretrained(
            str(self.model_path),
            local_files_only=True
        )

        self.model = AutoModelForCausalLM.from_pretrained(
            str(self.model_path),
            local_files_only=True,
            device_map="cpu"
        )

    def check(self, user_prompt):
        messages = [
            {
                "role": "system",
                "content": self.policy
            },
            {
                "role": "user",
                "content": user_prompt
            }
        ]

        text = self.tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=True
        )

        inputs = self.tokenizer(text, return_tensors="pt")

        output = self.model.generate(
            **inputs,
            max_new_tokens=10,
            do_sample=False
        )

        response = self.tokenizer.decode(
            output[0][inputs["input_ids"].shape[1]:],
            skip_special_tokens=True
        ).strip().upper()

        if "BLOCK" in response:
            decision = "BLOCK"
        elif "RESTRICT" in response:
            decision = "RESTRICT"
        else:
            decision = "ALLOW"

        return {
            "decision": decision,
            "reason": "Decision generated by local instruction-based safety evaluator",
            "raw_response": response
        }
